{% set name = "polarify" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polarify-{{ version }}.tar.gz
  sha256: 41e9b7df8bccefbec1294c7a59ddcc5cf9fdf960249f88a2cb520f67103c726c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - polars >=0.14.24,<0.21

test:
  imports:
    - polarify
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/polarify
  summary: Simplifying conditional Polars Expressions with Python 🐍 🐻‍❄️
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
    - '0xbe7a'
